# Generated by Django 2.0.2 on 2019-08-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
            ],
        ),
    ]
